from enum import Enum

class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    PLANNING = "PLANNING"
    RETRIEVING = "RETRIEVING"
    BUILDING_PROMPT = "BUILDING_PROMPT"
    GENERATING = "GENERATING"
    ANALYZING = "ANALYZING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    NEEDS_MANUAL_REVIEW = "NEEDS_MANUAL_REVIEW"


class ChapterStatus(str, Enum):
    DRAFT = "DRAFT"
    ANALYZING = "ANALYZING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    PUBLISHED = "PUBLISHED"


class IssueType(str, Enum):
    CONTEXT_ISSUE = "CONTEXT_ISSUE"
    PLANNER_ISSUE = "PLANNER_ISSUE"
    WRITING_ISSUE = "WRITING_ISSUE"
    POLICY_ISSUE = "POLICY_ISSUE"


class Severity(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
